language: node_js
node_js:
  - v4

addons:
  code_climate:

notifications:
  email:
    - contato@albertosouza.net

after_success:
- npm install coveralls
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js